/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./contexts/**/*.{js,jsx,ts,tsx}",
    "./hooks/**/*.{js,jsx,ts,tsx}",
    "./constants/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#006544",
        "outline": "#6d758c",
        "on-surface": "#dee5ff",
        "on-error": "#490006",
        "on-tertiary-container": "#004955",
        "primary-dim": "#58e7ab",
        "inverse-surface": "#faf8ff",
        "tertiary-fixed-dim": "#00cdeb",
        "outline-variant": "#40485d",
        "surface-container-high": "#141f38",
        "on-secondary-container": "#c3d1ea",
        "surface-container-lowest": "#000000",
        "surface-tint": "#69f6b8",
        "on-tertiary": "#005360",
        "inverse-on-surface": "#4d556b",
        "error-container": "#9f0519",
        "tertiary-container": "#00dcfd",
        "secondary": "#d5e3fd",
        "surface-variant": "#192540",
        "surface-bright": "#1f2b49",
        "on-secondary-fixed-variant": "#4e5c71",
        "tertiary": "#77e6ff",
        "secondary-container": "#3a485c",
        "on-secondary-fixed": "#324054",
        "surface-dim": "#060e20",
        "surface": "#060e20",
        "tertiary-dim": "#00cdeb",
        "primary-fixed-dim": "#58e7ab",
        "error": "#ff716c",
        "surface-container": "#0f1930",
        "inverse-primary": "#006d4a",
        "error-dim": "#d7383b",
        "primary": "#69f6b8",
        "on-secondary": "#455367",
        "surface-container-low": "#091328",
        "secondary-dim": "#c7d5ee",
        "on-error-container": "#ffa8a3",
        "on-tertiary-fixed": "#00343c",
        "on-surface-variant": "#a3aac4",
        "background": "#060e20",
        "on-tertiary-fixed-variant": "#005360",
        "on-background": "#dee5ff",
        "primary-container": "#06b77f",
        "primary-fixed": "#69f6b8",
        "secondary-fixed-dim": "#c7d5ee",
        "on-primary-container": "#002919",
        "surface-container-highest": "#192540",
        "on-primary-fixed": "#00452d",
        "tertiary-fixed": "#00dcfd",
        "secondary-fixed": "#d5e3fd",
        "on-primary": "#005a3c"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
};
